enum ProtocolKnowledgeStatus { documented, verified, suspected, unknown }

/// Direction from the SEQTRAK's perspective.
enum SeqtrakParameterDirection { bidirectional, deviceReceiveOnly }

enum SeqtrakParameter {
  trackVolume,
  trackPan,
  drumPitch,
  monoPolyChord,
  attackTime,
  decayReleaseTime,
  filterCutoff,
  filterResonance,
  reverbSend,
  delaySend,
  eqHighGain,
  eqLowGain,
  portamentoTime,
  portamentoSwitch,
  arpType,
  arpGate,
  arpSpeed,
  fmAlgorithm,
  fmModulationAmount,
  fmModulatorFrequency,
  fmModulatorFeedback,
  masterEffect1Parameter1,
  masterEffect1Parameter2,
  masterEffect1Parameter3,
  masterEffect2Parameter,
  masterEffect3Parameter,
  singleEffectParameter1,
  singleEffectParameter2,
  singleEffectParameter3,
  sendReverbParameter1,
  sendReverbParameter2,
  sendReverbParameter3,
  sendDelayParameter1,
  sendDelayParameter2,
  sendDelayParameter3,
  mute,
  solo,
  damperPedal,
  sostenuto,
  expressionControl,
}

class SeqtrakParameterDefinition {
  const SeqtrakParameterDefinition({
    required this.parameter,
    required this.name,
    required this.cc,
    required this.channels,
    required this.minimum,
    required this.maximum,
    required this.rangeDescription,
    required this.applicability,
    this.direction = SeqtrakParameterDirection.bidirectional,
    this.status = ProtocolKnowledgeStatus.documented,
    this.source = seqtrakUserGuideMidiSource,
  });

  final SeqtrakParameter parameter;
  final String name;
  final int cc;
  final Set<int> channels;
  final int minimum;
  final int maximum;
  final String rangeDescription;
  final String applicability;
  final SeqtrakParameterDirection direction;
  final ProtocolKnowledgeStatus status;
  final String source;

  bool supportsChannel(int channel) => channels.contains(channel);
  bool supportsValue(int value) => value >= minimum && value <= maximum;
}

const seqtrakUserGuideMidiSource =
    'https://manual.yamaha.com/mi/de/seqtrak/en/'
    'SEQTRAK_user_guide_En_D0_018.html';

const _allTracks = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
const _drumTracks = {1, 2, 3, 4, 5, 6, 7};
const _synthAndDxTracks = {8, 9, 10};
const _melodicTracks = {8, 9, 10, 11};
const _synthAndSamplerTracks = {8, 9, 11};
const _channel1 = {1};

const seqtrakParameterDefinitions = <SeqtrakParameterDefinition>[
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.trackVolume,
    name: 'Track Volume',
    cc: 7,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.trackPan,
    name: 'Track Pan',
    cc: 10,
    channels: _allTracks,
    minimum: 1,
    maximum: 127,
    rangeDescription: '1-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.drumPitch,
    name: 'Drum Pitch',
    cc: 25,
    channels: _drumTracks,
    minimum: 40,
    maximum: 88,
    rangeDescription: '40-88',
    applicability: 'DRUM',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.monoPolyChord,
    name: 'Mono/Poly/Chord',
    cc: 26,
    channels: _synthAndDxTracks,
    minimum: 0,
    maximum: 2,
    rangeDescription: '0=MONO, 1=POLY, 2=CHORD',
    applicability: 'SYNTH, DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.attackTime,
    name: 'Attack Time',
    cc: 73,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.decayReleaseTime,
    name: 'Decay/Release Time',
    cc: 75,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.filterCutoff,
    name: 'Filter Cutoff',
    cc: 74,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.filterResonance,
    name: 'Filter Resonance',
    cc: 71,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.reverbSend,
    name: 'Reverb Send',
    cc: 91,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.delaySend,
    name: 'Delay Send',
    cc: 94,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.eqHighGain,
    name: 'EQ - High Gain',
    cc: 20,
    channels: _allTracks,
    minimum: 40,
    maximum: 88,
    rangeDescription: '40-88',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.eqLowGain,
    name: 'EQ - Low Gain',
    cc: 21,
    channels: _allTracks,
    minimum: 40,
    maximum: 88,
    rangeDescription: '40-88',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.portamentoTime,
    name: 'Portamento Time',
    cc: 5,
    channels: _synthAndDxTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127 (0=OFF)',
    applicability: 'SYNTH, DX (must be mono)',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.portamentoSwitch,
    name: 'Portamento Switch',
    cc: 65,
    channels: _synthAndDxTracks,
    minimum: 0,
    maximum: 1,
    rangeDescription: '0=OFF, 1=ON',
    applicability: 'SYNTH, DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.arpType,
    name: 'ARP Type',
    cc: 27,
    channels: _synthAndDxTracks,
    minimum: 0,
    maximum: 16,
    rangeDescription: '0-16 (0=OFF)',
    applicability: 'SYNTH, DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.arpGate,
    name: 'ARP Gate',
    cc: 28,
    channels: _synthAndDxTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'SYNTH, DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.arpSpeed,
    name: 'ARP Speed',
    cc: 29,
    channels: _synthAndDxTracks,
    minimum: 0,
    maximum: 9,
    rangeDescription: '0-9',
    applicability: 'SYNTH, DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.fmAlgorithm,
    name: 'FM Algorithm',
    cc: 116,
    channels: {10},
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.fmModulationAmount,
    name: 'FM Modulation Amount',
    cc: 117,
    channels: {10},
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.fmModulatorFrequency,
    name: 'FM Modulator Frequency',
    cc: 118,
    channels: {10},
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.fmModulatorFeedback,
    name: 'FM Modulator Feedback',
    cc: 119,
    channels: {10},
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DX',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.masterEffect1Parameter1,
    name: 'Master Effect 1 - Assigned Parameter 1',
    cc: 102,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Master effect',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.masterEffect1Parameter2,
    name: 'Master Effect 1 - Assigned Parameter 2',
    cc: 103,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Master effect',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.masterEffect1Parameter3,
    name: 'Master Effect 1 - Assigned Parameter 3',
    cc: 104,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Master effect',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.masterEffect2Parameter,
    name: 'Master Effect 2 - Assigned Parameter',
    cc: 105,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Master effect',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.masterEffect3Parameter,
    name: 'Master Effect 3 - Assigned Parameter',
    cc: 106,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Master effect',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.singleEffectParameter1,
    name: 'Single Effect - Assigned Parameter 1',
    cc: 107,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.singleEffectParameter2,
    name: 'Single Effect - Assigned Parameter 2',
    cc: 108,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.singleEffectParameter3,
    name: 'Single Effect - Assigned Parameter 3',
    cc: 109,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sendReverbParameter1,
    name: 'Send Reverb - Assigned Parameter 1',
    cc: 110,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Send reverb',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sendReverbParameter2,
    name: 'Send Reverb - Assigned Parameter 2',
    cc: 111,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Send reverb',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sendReverbParameter3,
    name: 'Send Reverb - Assigned Parameter 3',
    cc: 112,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Send reverb',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sendDelayParameter1,
    name: 'Send Delay - Assigned Parameter 1',
    cc: 113,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Send delay',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sendDelayParameter2,
    name: 'Send Delay - Assigned Parameter 2',
    cc: 114,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Send delay',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sendDelayParameter3,
    name: 'Send Delay - Assigned Parameter 3',
    cc: 115,
    channels: _channel1,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'Send delay',
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.mute,
    name: 'Mute',
    cc: 23,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-63=OFF, 64-127=ON',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
    direction: SeqtrakParameterDirection.deviceReceiveOnly,
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.solo,
    name: 'Solo',
    cc: 24,
    channels: _allTracks,
    minimum: 0,
    maximum: 11,
    rangeDescription: '0=OFF, 1-11=TRACK 1-11',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
    direction: SeqtrakParameterDirection.deviceReceiveOnly,
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.damperPedal,
    name: 'Damper Pedal',
    cc: 64,
    channels: _melodicTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'SYNTH, DX, SAMPLER',
    direction: SeqtrakParameterDirection.deviceReceiveOnly,
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.sostenuto,
    name: 'Sostenuto',
    cc: 66,
    channels: _synthAndSamplerTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-63=OFF, 64-127=ON',
    applicability: 'SYNTH, SAMPLER',
    direction: SeqtrakParameterDirection.deviceReceiveOnly,
  ),
  SeqtrakParameterDefinition(
    parameter: SeqtrakParameter.expressionControl,
    name: 'Expression Control',
    cc: 11,
    channels: _allTracks,
    minimum: 0,
    maximum: 127,
    rangeDescription: '0-127',
    applicability: 'DRUM, SYNTH, DX, SAMPLER',
    direction: SeqtrakParameterDirection.deviceReceiveOnly,
  ),
];

SeqtrakParameterDefinition definitionFor(SeqtrakParameter parameter) =>
    seqtrakParameterDefinitions.singleWhere(
      (definition) => definition.parameter == parameter,
    );
